name: devel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - poetry=1.3.2
  - pytest=7.2
  - deepdiff=6.7.1
  - numpy=1.26.0
  - pandas=2.1.4
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - py3dmol=2.0.1.post1
  - rdkit=2023.03.3
  - rdfpy=1.0.0
